language: android
sudo: false
jdk: openjdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-28
script:
  - ./gradlew assembledebug  

deploy:
    provider: releases
    skip_cleanup: true
    api_key: "Wk41dTj7MJTw1bZA3xYMY4Bc1AbTg+x0y3B61ncCl0R60JKF0JTSEbRWssaoKl03nME1wSkQqUEH/4ytFXlr/7hFuOqluG0GnA3RzJEcjlA4KlbVpvLwtkG1jAN+88vu5nHTYQfZmAdryp3RsdjJXbUeIdH/Zg6cS6wJ4U7FYCM="
    file:  "app/build/outputs/apk/app-debug.apk"
    on:
      repo: grzegorznittner/chanu
      tags: true
